"""Added fields to user model

Revision ID: bb5a614ed8ec
Revises: 874387d99d0b
Create Date: 2022-04-10 12:38:36.582656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "bb5a614ed8ec"
down_revision = "874387d99d0b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("username", sa.String(length=30), nullable=False))
    op.add_column("users", sa.Column("email", sa.String(length=255), nullable=False))
    op.add_column(
        "users", sa.Column("password", sa.LargeBinary(length=60), nullable=False)
    )
    op.create_unique_constraint(None, "users", ["username"])
    op.create_unique_constraint(None, "users", ["email"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.drop_constraint(None, "users", type_="unique")
    op.drop_column("users", "password")
    op.drop_column("users", "email")
    op.drop_column("users", "username")
    # ### end Alembic commands ###
